#!/usr/bin/env python3
## EPITECH PROJECT, 2023
## Zappy-Mirror
## File description:
## zappy_ai
##

from AI.main import main

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(e)
        exit(84)
