name: GUI_Protocol request
description: request for implementation of GUI Protocol
title: "[GUI_Protocol]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: GUI_Protocol Description
      description: Describe the GUI_Protocol you are requesting
      placeholder: |
        {{default "Describe the GUI_Protocol you are requesting\n\nThe server responds:\nThe client sends:\n\n```c\ntypedef struct game_struct_s {\n  struct egg_head all_eggs;\n  struct clan_head all_clans;\n  int nb_trantorians;\n  int nb_eggs;\n  map_t *map;\n  int time_unit;\n} game_struct_t;\n```" feature-description}}
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: timeNeeded
    attributes:
      label: Time Needed
      description: How much time do you think this feature will take?
      multiple: false
      options:
        - 1-2 hours
        - 2-4 hours
        - 4-8 hours
        - 8-16 hours
        - 16-32 hours
        - 32-64 hours
        - 64-128 hours
        - 128+ hours
    validations:
      required: true
