name: GUI_Protocol request
description: request for implementation of GUI Protocol
title: "[GUI_Protocol]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: GUI_Protocol Description
      description: Describe the GUI_Protocol you are requesting
      placeholder: Exemple
      value: |
        the server responds: \"Your Text\"
        The client send: \"Your Text\"
      render: markdown
  - type: textarea
    id: exemple-structure-game
    attributes:
      label: Exemple of structure game
      placeholder: structure
      value: |
        ```c
        typedef struct game_struct_s {
          struct egg_head all_eggs;
          struct clan_head all_clans;
          int nb_trantorians;
          int nb_eggs;
          map_t *map;
          int time_unit;
        } game_struct_t;
        ```
    validations:
      required: true
  - type: dropdown
    id: timeNeeded
    attributes:
      label: Time Needed
      description: How much time do you think this feature will take?
      multiple: false
      options:
        - 1-2 hours
        - 2-4 hours
        - 4-8 hours
        - 8-16 hours
        - 16-32 hours
        - 32-64 hours
        - 64-128 hours
        - 128+ hours
    validations:
      required: true
