name: GUI_Protocol request
description: request for implementation of GUI Protocol
title: "[GUI Protocol]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: GUI Protocol Description
      description: Describe the GUI_Protocol you are requesting
      placeholder: Exemple
      value: |
        The client send: "Your Text" which correspond to ""
        the server responds: "Your Text"
      render: Markdown
  - type : textarea
    id: exemple-image
    attributes:
      label: GUI Protocol image
      placeholder: imageexemple
      value: |
        --------------------

        ![Capture d'écran 2023-06-10 224150](https://github.com/Miou-zora/Zappy-Mirror/assets/87119218/22aac238-f85f-4736-a5a9-b665f3feeb6b)

        --------------------

  - type: textarea
    id: exemple-structure-game
    attributes:
      label: Exemple of game structure
      placeholder: structure
      value: |
        ```c
        typedef struct game_struct_s {
          struct egg_head all_eggs;
          struct clan_head all_clans;
          int nb_trantorians;
          int nb_eggs;
          map_t *map;
          int time_unit;
        } game_struct_t;
        ```
    validations:
      required: true
  - type: dropdown
    id: timeNeeded
    attributes:
      label: Time Needed
      description: How much time do you think this feature will take?
      multiple: false
      options:
        - 1-2 hours
        - 2-4 hours
        - 4-8 hours
        - 8-16 hours
        - 16-32 hours
        - 32-64 hours
        - 64-128 hours
        - 128+ hours
    validations:
      required: true
