# Created by @Miou-zora (please keep it ;) )

name: mirror

on:
  push:
    branches-ignore:
     - 'ga-ignore-**'
  pull_request:
    branches-ignore:
     - 'ga-ignore-**'

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-YEP-400-NAN-4-1-zappy-alexandre.franquet.git"
  EXECUTABLES: "zappy_server,zappy_gui,zappy_ai"

jobs:
  check_repository_cleanliness:
    name: Checks if the repository is clean and void of any unwanted files (temp files, binary files, etc.)
    runs-on: ubuntu-latest
    env:
      UNWANTED_REGEX: ^(?!.*tests\/).*gc(no|da|ov)$|(.*\.(a|o|so))$|(.*~)$|^(#.*#)$|(.*(?i)pain_au_chocolat.*)|^tmp\/.*|.*\/tmp\/.*
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout glm repository
        uses: actions/checkout@v3
        with:
          repository: g-truc/glm
          path: glm

      - name: Find temp files in all directories
        run: |
          UNWANTED_FILES=$(find . -type f -printf '%P\n' | { grep -P "${{ env.UNWANTED_REGEX }}" || true; })
          if [ "$UNWANTED_FILES" != "" ]; then
              IFS=$'\n'$'\r'
              for LINE in $UNWANTED_FILES; do
                  echo "::error file=${LINE},line=1,col=1,title=Unwanted file detected::${LINE}"
              done
              echo "FAIL_TASK=true" >> "$GITHUB_ENV"
          else
              echo "FAIL_TASK=false" >> "$GITHUB_ENV"
          fi

      - name: Fail if needed
        if: env.FAIL_TASK == 'true'
        run: exit 1

  check_coding_style:
    needs: [check_repository_cleanliness]
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v3
      - id: check_coding_style
        run: check.sh $(pwd) $(pwd)
        continue-on-error: true
        #redirect to a specific line in a file when a Github Actions is clicked
        # so we need to include the file name, the line number and the error message
        # as this example : echo "::error file=path/to/file.cpp,line=42::Error message"
        # if the file is empty (no coding style error) then we print a notice and continue the workflow
        # if the file is not empty (coding style error) then we print an error and stop the workflow
      - name: Anotation of the coding style
        run: |
          cat coding-style-reports.log | while read line; do
            error_code=$(echo "$line" | cut -d ':' -f 4)
            if [[ "$error_code" != "C-G4" && "$error_code" != "C-O1" ]]; then
              echo "$line" >> coding-style-reports-updated.log
            fi
          done
          if [ -s coding-style-reports-updated.log ]; then
            mv coding-style-reports-updated.log coding-style-reports.log
            echo "::error::Coding style errors found. Please check the log file."
            exit 1
          else
            echo "::notice::No coding style error found."
          fi
        continue-on-error: false

  check_program_compilation:
    name: Checks if the program compiles correctly and executables files got created
    runs-on: ubuntu-latest
    needs: [check_coding_style]
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo dnf install -y glew-devel glfw-devel glm-devel

      - run: make
        timeout-minutes: 3

      - run: make clean

      - name: Verifies that files are present and executable
        run: |
          echo "FAIL_TASK=false" >> "$GITHUB_ENV"
          SEARCH_BINARIES="${{ env.EXECUTABLES }}"
          IFS=$','
          for BIN in $SEARCH_BINARIES; do
              if [ ! -f "${BIN}" ]; then
                  echo "::error file=${BIN},title=Binary not found::${BIN}"
                  echo "FAIL_TASK=true" >> "$GITHUB_ENV"
              fi
              if [ ! -x "${BIN}" ]; then
                  echo "::error file=${BIN},title=Binary not executable::${BIN}"
                  echo "FAIL_TASK=true" >> "$GITHUB_ENV"
              fi
          done

      - name: Fail if needed
        if: env.FAIL_TASK == 'true'
        run: exit 1

      - name: Starts tests
        run: make tests_run
        timeout-minutes: 3

  push_to_mirror:
    name: Pushes the current repository files to a given mirror repository
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: [check_program_compilation]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
